context:
  version: 0.29.47

package:
  name: bicep
  version: ${{ version }}

source:
  git: https://github.com/Azure/bicep
  tag: v${{ version }}

build:
  number: 0

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - bicep --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files_bicep/
    - license-files_bicep-langserver/
  summary: Bicep is a declarative language for describing and deploying Azure resources
  homepage: https://github.com/Azure/bicep
  repository: https://github.com/Azure/bicep

extra:
  recipe-maintainers:
    - danielnachun
